"""empty message

Revision ID: 11235a2a10dc
Revises: 1367e8962bd5
Create Date: 2023-10-20 15:43:08.248183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11235a2a10dc'
down_revision = '1367e8962bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=6), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_scores', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('age_group')

    # ### end Alembic commands ###
