"""empty message

Revision ID: 1367e8962bd5
Revises: 14d646a773dc
Create Date: 2023-10-20 15:41:37.298712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1367e8962bd5'
down_revision = '14d646a773dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_scores')
    # ### end Alembic commands ###
