"""empty message

Revision ID: 14d646a773dc
Revises: 1ee15563a052
Create Date: 2023-10-20 09:43:22.015514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d646a773dc'
down_revision = '1ee15563a052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('max_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('assessment_option', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_option', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('max_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
