"""empty message

Revision ID: 23ea31dd82ee
Revises: 8864300f74e3
Create Date: 2023-10-22 01:02:00.022228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ea31dd82ee'
down_revision = '8864300f74e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('title_sw',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('assessment_option', schema=None) as batch_op:
        batch_op.alter_column('text_sw',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.alter_column('text_sw',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('check_in', schema=None) as batch_op:
        batch_op.alter_column('title_sw',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('check_in_option', schema=None) as batch_op:
        batch_op.alter_column('text_sw',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_in_option', schema=None) as batch_op:
        batch_op.alter_column('text_sw',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('check_in', schema=None) as batch_op:
        batch_op.alter_column('title_sw',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.alter_column('text_sw',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('assessment_option', schema=None) as batch_op:
        batch_op.alter_column('text_sw',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('title_sw',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
