"""empty message

Revision ID: 325182f3eb14
Revises: 11235a2a10dc
Create Date: 2023-10-20 15:52:50.422631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325182f3eb14'
down_revision = '11235a2a10dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_scores', schema=None) as batch_op:
        batch_op.create_foreign_key("score_assessment", 'assessment', ['assessment_id'], ['id'])
        batch_op.create_foreign_key("score_user", 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_scores', schema=None) as batch_op:
        batch_op.drop_constraint("score_assessment", type_='foreignkey')
        batch_op.drop_constraint("score_user", type_='foreignkey')

    # ### end Alembic commands ###
