"""empty message

Revision ID: 39490f396c55
Revises: 853a5f2d461f
Create Date: 2023-10-19 22:27:43.592432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39490f396c55'
down_revision = '853a5f2d461f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('assessment_question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_question_id'], ['assessment_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_option')
    op.drop_table('assessment_question')
    op.drop_table('assessment')
    # ### end Alembic commands ###
