"""empty message

Revision ID: 729351be2837
Revises: b45f824d9c27
Create Date: 2023-10-28 23:48:34.874540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729351be2837'
down_revision = 'b45f824d9c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
