"""empty message

Revision ID: 853a5f2d461f
Revises: 88ed75712146
Create Date: 2023-10-19 09:08:45.778357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853a5f2d461f'
down_revision = '88ed75712146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_in_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_in.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_in_option')
    op.drop_table('check_in')
    # ### end Alembic commands ###
