"""empty message

Revision ID: 8864300f74e3
Revises: 325182f3eb14
Create Date: 2023-10-22 00:16:33.756132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8864300f74e3'
down_revision = '325182f3eb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_sw', sa.String(), nullable=True))

    with op.batch_alter_table('assessment_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_sw', sa.String(), nullable=True))

    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_sw', sa.String(), nullable=True))

    with op.batch_alter_table('check_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_sw', sa.String(), nullable=True))

    with op.batch_alter_table('check_in_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_sw', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_in_option', schema=None) as batch_op:
        batch_op.drop_column('text_sw')

    with op.batch_alter_table('check_in', schema=None) as batch_op:
        batch_op.drop_column('title_sw')

    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.drop_column('text_sw')

    with op.batch_alter_table('assessment_option', schema=None) as batch_op:
        batch_op.drop_column('text_sw')

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_column('title_sw')

    # ### end Alembic commands ###
